### ISSUE TITLE
Got env: node\r: No such file or directory on OSX

### ISSUE THREAD

**Issue by sotayamashita** [danilolekovic/iode#12]
When run any command, I got `env: node\r: No such file or directory` so I specified a file but I also got the error.

```
$ stripes -h
env: node\r: No such file or directory
```

Is there any solution? Thanks in advance.

**Comment by danilolekovic** [comment]
Hi, thanks for reporting this issue.

What operating system are you running?

**Comment by sotayamashita** [comment]
My operating system is OS X 10.10

**Comment by danilolekovic** [comment]
Don't have any machines running OS X so I can't really debug this. Perhaps the new version of Stripes (0.0.8) will work?

**Comment by sotayamashita** [comment]
I upgraded to v0.0.8 but it still does not work.

**Comment by danilolekovic** [comment]
My apologies. I've figured out why this isn't working. It's due to Windows having \r\n for line endings and UNIX-based systems having only \n. I may have fixed the error in the latest version (v0.0.82) by refreshing line endings. If it still doesn't work:

``` sh
$ brew install dos2unix
$ dos2unix <insert node-modules directory path here>/stripes/bin/stripes
```

**Comment by sotayamashita** [comment]
Finally, it works well.

**Comment by danilolekovic** [comment]
Awesome, thanks! :smiley:
